apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "f7f3d031b833bff31031e2f25fe325aa6f0555c1"
        buildDate: "20220316170647"
    spec:
      containers:
        - name: products
          image: host.k3d.internal:5090/products:latest
          ports:
            - containerPort: 8080
              name: 8080-tcp
